package fantasyf1.domain;

import java.util.LinkedHashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;

@Data
@Entity
public class Engine extends AutogeneratedPK implements Comparable<Engine>, PointScorer  {
	
	@Column(unique = true)
	private String name;
	private int price;

	private long totalPoints;
	@ElementCollection(fetch = FetchType.EAGER)
	private Map<Integer, Integer> pointsPerEvent = new LinkedHashMap<>();

	public Engine() {
	}

	public Engine(final String name, final int price) {
		this.name = name;
		this.price = price;
	}

	@Override
	public boolean equals(final Object otherDriver) {
		if (otherDriver instanceof Engine) {
			if (name.equalsIgnoreCase(((Engine) otherDriver).getName())) {
				return true;
			}
		}
		return false;
	}

	@Override
	public int hashCode() {
		return name.hashCode();
	}

	@Override
	public String toString() {
		return getName();
	}

	@Override
	public int compareTo(final Engine o) {
		return name.compareToIgnoreCase(o.getName());
	}
}