package net.ddns.f1.domain;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import lombok.Data;

@MappedSuperclass
@Data
public abstract class AutogeneratedPK {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	Integer id;
}
